#include <iostream>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_mixer.h>
#include <SDL_ttf.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string>
//#include <sstream>
#include <fstream>
#include <istream>
//#include <SDL_opengl.h>
//#include <random>
#include <math.h>